// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7MODUaIOaZOzeSdBdTOq4mMBZ7B7CjW8',
    appId: '1:263151126635:web:9d800cd568a477d3e0892e',
    messagingSenderId: '263151126635',
    projectId: 'tasktrakr-app',
    authDomain: 'tasktrakr-app.firebaseapp.com',
    storageBucket: 'tasktrakr-app.firebasestorage.app',
    measurementId: 'G-SPNN30XTPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjJGN4TGCom8CWwQS5RvOkEVWDMAs4cx0',
    appId: '1:263151126635:android:3c538c26487d2133e0892e',
    messagingSenderId: '263151126635',
    projectId: 'tasktrakr-app',
    storageBucket: 'tasktrakr-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLM47NPyuA39auW8lFWT5pbCWA1Y-TPEY',
    appId: '1:263151126635:ios:fc306b9db5ad907ae0892e',
    messagingSenderId: '263151126635',
    projectId: 'tasktrakr-app',
    storageBucket: 'tasktrakr-app.firebasestorage.app',
    iosBundleId: 'com.tasktrakr.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLM47NPyuA39auW8lFWT5pbCWA1Y-TPEY',
    appId: '1:263151126635:ios:fc306b9db5ad907ae0892e',
    messagingSenderId: '263151126635',
    projectId: 'tasktrakr-app',
    storageBucket: 'tasktrakr-app.firebasestorage.app',
    iosBundleId: 'com.tasktrakr.app',
  );
}
